In [ ]:
'''
PLEASE UPLOAD "util.py" FILE ON COLAB MANUALLY TO RUN CONFUSION MATRIX
'''

import numpy as np
import scipy
import matplotlib.pyplot as plt
from keras.datasets import mnist
# from util import func_confusion_matrix


# load (downloaded if needed) the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()


# transform each image from 28 by28 to a 784 pixel vector
pixel_count = x_train.shape[1] * x_train.shape[2]
x_train = x_train.reshape(x_train.shape[0], pixel_count).astype('float32')
x_test = x_test.reshape(x_test.shape[0], pixel_count).astype('float32')

# normalize inputs from gray scale of 0-255 to values between 0-1
x_train = x_train / 255
x_test = x_test / 255

# Please write your own codes in responses to the homework assignment 4

split_size = 50000

# Training set
sub1 = x_train[:split_size]
sub1_labels = y_train[:split_size]

# Validation set
sub2 = x_train[split_size:]
sub2_labels = y_train[split_size:]



In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 


#Paramater set #1
rate = 0.001 #learning rate
neu = 256 #Number of neurons
act_fnc = 'logistic' #sigmoid activation
out_fnc = 'softmax' #softmax output activation

#Define model   2 hidden layers
model = MLPClassifier(hidden_layer_sizes = (neu, neu), 
                      learning_rate_init = rate, 
                      activation = act_fnc)

#Train model using subset of size 50,000
model.fit(sub1, sub1_labels)


#define output function
model.out_activation_ = out_fnc

#Predict over validation set 
pred = model.predict(sub2)

# execute the util.py file

execfile('./util.py')

matrix, accuracy, recall, preci = func_confusion_matrix(sub2_labels, pred)

#Remove deprecation warnings


#Display confusion matrix
print(matrix)
print("\n")

#Display Accuracy, per-class precision and recall
print("Accuracy: {}\n".format(accuracy))
print("Per-class recall rate: {}\n".format(recall))
print("Per-class precision rate: {}\n".format(preci))



[[ 979    0    2    1    0    1    2    1    2    3]
 [   0 1056    1    2    0    0    2    2    1    0]
 [   1    2  974    4    0    1    1    2    5    0]
 [   0    0    4 1008    0    8    0    1    7    2]
 [   0    5    3    0  962    0    2    1    1    9]
 [   2    0    4   10    0  882    9    1    5    2]
 [   2    0    0    0    2    2  959    0    2    0]
 [   0    2    2    2    2    0    0 1077    0    5]
 [   1    1    2    6    1    3    1    0  990    4]
 [   2    2    0    2   12    2    0    4    4  933]]


Accuracy: 0.982

Per-class recall rate: [0.98789102 0.9924812  0.98383838 0.97864078 0.97863683 0.96393443
 0.99172699 0.98807339 0.98116947 0.97086368]

Per-class precision rate: [0.99189463 0.98876404 0.98185484 0.97391304 0.98263534 0.9810901
 0.98258197 0.98898072 0.97345133 0.97390397]



In [ ]:
#Set two parameters

rate = 0.01 #learning rate
neu_1 = 150 #Number of neurons
neu_2 = 100
neu_3 = 50
act_fnc = 'logistic' #sigmoid activation
out_fnc = 'identity' #linear output activation

          # 3 hidden layers
model = MLPClassifier(hidden_layer_sizes = (neu_1, neu_2, neu_3), 
                      learning_rate_init = rate, 
                      activation = act_fnc)

#Train model using subset of size 50,000
model.fit(sub1, sub1_labels)

import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning) 

#define output function
model.out_activation_ = out_fnc

#Predict over validation set 
pred = model.predict(sub2)

# execute the util.py file
execfile('./util.py')

matrix, accuracy, recall, preci = func_confusion_matrix(sub2_labels, pred)

#Display confusion matrix
print(matrix)
print("\n")

#Display Accuracy, per-class precision and recall
print("Accuracy: {}\n".format(accuracy))
print("Per-class recall rate: {}\n".format(recall))
print("Per-class precision rate: {}\n".format(preci))



[[ 979    0    4    0    0    0    2    0    2    4]
 [   0 1051    4    1    0    1    3    1    3    0]
 [   3    2  959   13    3    1    2    3    4    0]
 [   2    0    3 1006    0    6    0    1    7    5]
 [   0    3    0    0  963    0    6    2    1    8]
 [   2    0    2   23    2  853   19    2    4    8]
 [   2    0    0    1    1    0  962    0    1    0]
 [   0    2    4    6    1    0    0 1072    0    5]
 [   2    4    2    9    1    4    1    0  981    5]
 [   2    2    0    2   17    5    0   10    7  916]]


Accuracy: 0.9742

Per-class recall rate: [0.98789102 0.98778195 0.96868687 0.97669903 0.97965412 0.93224044
 0.99482937 0.98348624 0.97224975 0.95317378]

Per-class precision rate: [0.98689516 0.98778195 0.9805726  0.94816211 0.97469636 0.98045977
 0.96683417 0.98258478 0.97128713 0.96319664]



In [ ]:
#Set three Parameterss
rate = 0.0001 #learning rate
neu_1 = 300 
neu_2 = 200
neu_3 = 100
neu_4  = 50
act_fnc = 'tanh' #sigmoid activation
out_fnc = 'logistic' #linear output activation

# Four hidden layers
model = MLPClassifier(hidden_layer_sizes = (neu_1, neu_2, neu_3, neu_4), 
                      learning_rate_init = rate,
                      activation = act_fnc)

#Train model using subset of size 50,000
model.fit(sub1, sub1_labels)

import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning) 

#define output function
model.out_activation_ = out_fnc

#Predict over validation set 
pred = model.predict(sub2)

# execute the util.py file
execfile('./util.py')

matrix, accuracy, recall, preci = func_confusion_matrix(sub2_labels, pred)

#Display confusion matrix
print(matrix)
print("\n")

#Display Accuracy, per-class precision and recall
print("Accuracy: {}\n".format(accuracy))
print("Per-class recall rate: {}\n".format(recall))
print("Per-class precision rate: {}\n".format(preci))


[[ 976    0    4    1    1    0    2    2    3    2]
 [   0 1053    1    4    0    0    2    2    2    0]
 [   2    1  977    4    0    1    1    0    4    0]
 [   0    0    4 1003    0   11    0    2    7    3]
 [   0    6    1    0  959    0    2    1    2   12]
 [   3    0    3   13    1  875    8    1    7    4]
 [   3    0    0    0    0    0  961    0    3    0]
 [   0    3    5    3    2    0    0 1072    1    4]
 [   1    1    5    6    0    1    1    0  989    5]
 [   2    2    0    5    9    4    0    7    3  929]]


Accuracy: 0.9794

Per-class recall rate: [0.98486377 0.98966165 0.98686869 0.97378641 0.97558494 0.95628415
 0.99379524 0.98348624 0.98017839 0.96670135]

Per-class precision rate: [0.98885512 0.98780488 0.977      0.9653513  0.98662551 0.9809417
 0.98362334 0.98620055 0.96865818 0.96871741]



In [ ]:
#Set four parameters
rate = 0.001 #learning rate
neu_1 = 200 #Number of neurons
neu_2 = 150
act_fnc = 'tanh' #sigmoid activation
out_fnc = 'softmax' #softmax output activation

model = MLPClassifier(hidden_layer_sizes = (neu_1, neu_2), 
                      learning_rate_init = rate, 
                      activation = act_fnc)

#Train model using subset of size 50,000
model.fit(sub1, sub1_labels)

import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning) 

#define output function
model.out_activation_ = out_fnc

#Predict over validation set 
pred = model.predict(sub2)

# execute the util.py file
execfile('./util.py')

matrix, accuracy, recall, preci = func_confusion_matrix(sub2_labels, pred)

#Display confusion matrix
print(matrix)
print("\n")

#Display Accuracy, per-class precision and recall
print("Accuracy: {}\n".format(accuracy))
print("Per-class recall rate: {}\n".format(recall))
print("Per-class precision rate: {}\n".format(preci))

[[ 976    0    5    0    1    1    3    1    1    3]
 [   0 1054    1    2    0    1    3    1    2    0]
 [   1    1  975    2    2    1    0    3    5    0]
 [   0    0    5 1007    0    5    0    2    9    2]
 [   0    3    1    0  966    0    0    1    2   10]
 [   2    0    3    5    1  882   11    0    6    5]
 [   3    1    1    0    1    1  958    0    2    0]
 [   0    3    2    2    3    0    0 1073    1    6]
 [   1    0    3    5    0    2    1    2  991    4]
 [   3    2    0    3    7    4    0    7    4  931]]


Accuracy: 0.9813

Per-class recall rate: [0.98486377 0.9906015  0.98484848 0.9776699  0.982706   0.96393443
 0.99069286 0.98440367 0.98216056 0.96878252]

Per-class precision rate: [0.98985801 0.9906015  0.97891566 0.98148148 0.98470948 0.98327759
 0.98155738 0.98440367 0.96871945 0.96878252]



**QUESTION II**

In [ ]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 


#Set four parameters
rate = 0.001 #learning rate
neu_1 = 200 #Number of neurons
neu_2 = 150

act_fnc = 'tanh' #sigmoid activation
out_fnc = 'softmax' #softmax output activation

model = MLPClassifier(hidden_layer_sizes = (neu_1, neu_2), 
                      learning_rate_init = rate, 
                      activation = act_fnc)


model.fit(sub1,sub1_labels)

#define output function
model.out_activation_ = out_fnc
'''
Now we use the test set (10,000) to predict and visualize the incorrect ones
'''
pred = model.predict(x_test)

# execute the util.py file
execfile('./util.py')

matrix, accuracy, recall, preci = func_confusion_matrix(sub2_labels, pred)

#Display confusion matrix
print(matrix)
print("\n")

#Display Accuracy, per-class precision and recall
print("Accuracy: {}\n".format(accuracy))
print("Per-class recall rate: {}\n".format(recall))
print("Per-class precision rate: {}\n".format(preci))

[[110 113 118 101  93  87  83  97  95  94]
 [113 117 106 104 109  88  92 118 108 109]
 [103 110 101 106 101  76  95  86 108 104]
 [101 113 106 104  98  79 105 120  98 106]
 [107 111  98  98  96  80  95  97 108  93]
 [ 91 103  90  91  85  86  83 103  95  88]
 [ 71 106  94 111  94 103 102  89  83 114]
 [101 135 107 118 113 102 110 120  94  90]
 [101 114 114 100 104  93  89 102  90 102]
 [ 91 113 105  82  95  86 102  97  89 101]]


Accuracy: 0.1027

Per-class recall rate: [0.11099899 0.10996241 0.1020202  0.10097087 0.09766022 0.09398907
 0.10548087 0.11009174 0.08919722 0.10509886]

Per-class precision rate: [0.11122346 0.1030837  0.09720885 0.10246305 0.09716599 0.09772727
 0.10669456 0.11661808 0.09297521 0.1008991 ]

